# -*- coding: utf-8 -*-
"""Stegano.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNZMigt7v4ui7cnCZi-6EnFUAQSi-Qk4
"""

from google.colab import files
from PIL import Image
import cv2
import numpy as np
import io
import matplotlib.pyplot as plt

def calculate_psnr(original, compressed):
    mse = np.mean((original - compressed) ** 2)
    if mse == 0:
        return float('inf')
    max_pixel = 255.0
    psnr = 20 * np.log10(max_pixel / np.sqrt(mse))
    return psnr

# Meminta pengguna untuk mengunggah file
uploaded = files.upload()

# Ambil nama file gambar dari dictionary 'uploaded'
# Gantilah 'nama_gambar.jpg' dengan nama file yang sesuai
nama_file_gambar = 'pmd.png'

# Baca gambar dari objek byte
gambar_byte = uploaded['pmd.png']

# Konversi objek byte menjadi objek gambar menggunakan PIL
gambar = Image.open(io.BytesIO(gambar_byte))

# Konversi gambar PIL menjadi array NumPy
gambar_array = np.array(gambar)

# Menampilkan gambar asli
print("Gambar Asli:")
plt.imshow(gambar_array / 255.0)  # Normalisasi nilai antara 0 dan 1
plt.axis('off')
plt.show()

# Simpan gambar asli untuk perhitungan PSNR
cv2.imwrite('pmd.png', cv2.cvtColor(gambar_array, cv2.COLOR_RGB2BGR))

# Lakukan proses kompresi atau manipulasi citra (sesuai kebutuhan)

# Misalnya, definisikan dan inisialisasi compressed_image
compressed_image = cv2.cvtColor(gambar_array, cv2.COLOR_RGB2BGR)  # Ganti ini dengan logika kompresi Anda

# Simpan citra hasil kompresi untuk perhitungan PSNR
cv2.imwrite('pmdcompres.png', compressed_image)

# Memuat citra asli dan citra terkompresi
original_image = cv2.imread('pmd.png')
compressed_image = cv2.imread('pmdcompres.png')

# Ubah citra menjadi tipe data float32
original_image = original_image.astype(np.float32)
compressed_image = compressed_image.astype(np.float32)

# Hitung PSNR
psnr_value = calculate_psnr(original_image, compressed_image)

# Tampilkan hasil PSNR
print(f"\nPSNR Value: {psnr_value} dB")

# Menampilkan gambar terkompresi (jika ada)
print("\nGambar Terkompresi:")
plt.imshow(compressed_image / 255.0)  # Normalisasi nilai antara 0 dan 1
plt.axis('off')
plt.show()